### ISSUE TITLE
Log test fails on travis

### ISSUE THREAD

**Issue by yosefd** [anodejs/node-gits#4]

**Comment by eladb** [comment]
What is "log test"?

**Comment by yosefd** [comment]
Test case log fails when running on travis, while works OK in our windows env

The failure details are:

---

git -- stderr:

204git -- git log --format=%ce^^%cd^^%s 48298 (cwd: 48298 )

205git -- exit code: 128

206git -- stdout:

207git -- stderr: fatal: ambiguous argument '48298': unknown revision or path not in the working tree.

208Use '--' to separate paths from revisions

209

210undefined

211

212/home/vagrant/builds/anodejs/node-gits/tests/tests.js:99

213 test.equals(commits.length, 4);

214 ^

215TypeError: Cannot read property 'length' of undefined

216 at /home/vagrant/builds/anodejs/node-gits/tests/tests.js:99:3

---

The test is disabled and need to be investigated.

**Comment by eladb** [comment]
Thanks

On 1/11/12 6:05 PM, "Yosef Dinerstein"
<reply+i-2805996-e9a049720a820cf4b155ddcf2e53344d07430d2d-598796@reply.gith
ub.com> wrote:

**Comment by gilad61** [comment]
Fixed - 
Travis failed because in log test "dir" was a relative path.
Needed to add "dir = path.resolve(dir)" to make full path instead of relative.

**Comment by eladb** [comment]
Cool. Thanks
